### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by OmarMohammed88** [UBC-NLP/marbert#1]
Could you please provide cktp file for both models?

**Comment by Nagoudi** [comment]
Hello, 
Both models can be downloaded from our hugging face repo:  
 **ARBERT**: [https://huggingface.co/UBC-NLP/MARBERT/tree/main](https://huggingface.co/UBC-NLP/ARBERT/tree/main)
**MARBERT**: [https://huggingface.co/UBC-NLP/MARBERT/tree/main](https://huggingface.co/UBC-NLP/MARBERT/tree/main)

**Comment by OmarMohammed88** [comment]
yeah I noticed that, but I am looking for ckpt files also

**Comment by elmadany** [comment]
Thanks, @OmarMohammed88 for your interest in our models
We updated the [download section] (https://github.com/UBC-NLP/marbert/blob/main/README.md#6-download-arbert-and-marbert-checkpoints) by adding the download links for PyTorch and Tensoreflow checkpoints section

**Comment by Alymostafa** [comment]
@elmadany 
I tried the checkpoints for both models, but it gives me this error. 
```
model.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator? 
```
I tried most of the solutions in TensorFlow issues, but still not working.

**Comment by Nagoudi** [comment]
Hi @Alymostafa, 

We will release a public **Colab** demo soon.

**Comment by elmadany** [comment]
@Alymostafa
We update the compressed checkpoints files. you can redownload it again and try 
Moreover, we add a demo for MARBERT Fine-Tuning with PyTorch checkpoint for Sentiment Analysis on the AJGT dataset Colab
https://github.com/UBC-NLP/marbert#4-how-to-use-arbert-and-marbert
