### ISSUE TITLE
Marbert-v2 lost again

### ISSUE THREAD

**Issue by ghost** [UBC-NLP/marbert#11]
I can't find marbert v2 I was using it only yesterday.

**Comment by elmadany** [comment]
Thank you for your interest in our models. 
We will release it soon

**Comment by Mohamed-Aziz-Ben-Nessir** [comment]
hello, now I also lost arat5 tweet base, is this going to be a long-term removal or are you guys planning to release them again? if so can you please indicate when approximately (a week, a month, a year,...)
